=== JohnnyYuVe/CONSEGNA-3/PRODOTTO_DATA.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT root (record+)>
<!ELEMENT record (ID_ARTICOLO , CODICE_ART , NOME_ARTICOLO , NOME_BRAND , MADE_IN , COMPOSIZIONE , TAGLIA , PREZZO_UNITARIO)>
<!ELEMENT  ID_ARTICOLO 	 (#PCDATA)>
<!ELEMENT  CODICE_ART 	 (#PCDATA)>
<!ELEMENT  NOME_ARTICOLO (#PCDATA)>
<!ELEMENT  NOME_BRAND 	 (#PCDATA)>
<!ELEMENT  MADE_IN  	 (#PCDATA)>
<!ELEMENT  COMPOSIZIONE  (#PCDATA)>
<!ELEMENT  TAGLIA 		 (#PCDATA)>
<!ELEMENT  PREZZO_UNITARIO (#PCDATA)>

=== JohnnyYuVe/CONSEGNA-3/PRODOTTO_DATA.XML
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE root SYSTEM "PRODOTTO_DATA.dtd">

<root>
	<record>
		<ID_ARTICOLO>1</ID_ARTICOLO>
		<CODICE_ART>20002Z001</CODICE_ART>
		<NOME_ARTICOLO>T-shirt shark</NOME_ARTICOLO>
		<NOME_BRAND>palm angels</NOME_BRAND>
		<MADE_IN>china</MADE_IN>
		<COMPOSIZIONE>cotone</COMPOSIZIONE>
		<TAGLIA>S</TAGLIA>
		<PREZZO_UNITARIO>44.50</PREZZO_UNITARIO>
	</record>
	<record>
		<ID_ARTICOLO>2</ID_ARTICOLO>
		<CODICE_ART>20002Z002</CODICE_ART>
		<NOME_ARTICOLO>T-shirt shark</NOME_ARTICOLO>
		<NOME_BRAND>palm angels</NOME_BRAND>
		<MADE_IN>china</MADE_IN>
		<COMPOSIZIONE>cotone</COMPOSIZIONE>
		<TAGLIA>M</TAGLIA>
		<PREZZO_UNITARIO>44.50</PREZZO_UNITARIO>
	</record>
	<record>
		<ID_ARTICOLO>3</ID_ARTICOLO>
		<CODICE_ART>20002Z003</CODICE_ART>
		<NOME_ARTICOLO>T-shirt shark</NOME_ARTICOLO>
		<NOME_BRAND>palm angels</NOME_BRAND>
		<MADE_IN>china</MADE_IN>
		<COMPOSIZIONE>cotone</COMPOSIZIONE>
		<TAGLIA>L</TAGLIA>
		<PREZZO_UNITARIO>44.50</PREZZO_UNITARIO>
	</record>
	<record>
		<ID_ARTICOLO>4</ID_ARTICOLO>
		<CODICE_ART>20002Z004</CODICE_ART>
		<NOME_ARTICOLO>T-shirt teddy</NOME_ARTICOLO>
		<NOME_BRAND>dor bell</NOME_BRAND>
		<MADE_IN>italy</MADE_IN>
		<COMPOSIZIONE>cotone</COMPOSIZIONE>
		<TAGLIA>S</TAGLIA>
		<PREZZO_UNITARIO>44.50</PREZZO_UNITARIO>
	</record>
	<record>
		<ID_ARTICOLO>5</ID_ARTICOLO>
		<CODICE_ART>20002Z005</CODICE_ART>
		<NOME_ARTICOLO>T-shirt teddy</NOME_ARTICOLO>
		<NOME_BRAND>dor bell</NOME_BRAND>
		<MADE_IN>italy</MADE_IN>
		<COMPOSIZIONE>cotone</COMPOSIZIONE>
		<TAGLIA>M</TAGLIA>
		<PREZZO_UNITARIO>44.50</PREZZO_UNITARIO>
	</record>
	<record>
		<ID_ARTICOLO>6</ID_ARTICOLO>
		<CODICE_ART>20002Z006</CODICE_ART>
		<NOME_ARTICOLO>T-shirt teddy</NOME_ARTICOLO>
		<NOME_BRAND>dor bell</NOME_BRAND>
		<MADE_IN>italy</MADE_IN>
		<COMPOSIZIONE>cotone</COMPOSIZIONE>
		<TAGLIA>L</TAGLIA>
		<PREZZO_UNITARIO>44.50</PREZZO_UNITARIO>
	</record>
	<record>
		<ID_ARTICOLO>7</ID_ARTICOLO>
		<CODICE_ART>20002Z007</CODICE_ART>
		<NOME_ARTICOLO>Pantalone svasato</NOME_ARTICOLO>
		<NOME_BRAND>etro</NOME_BRAND>
		<MADE_IN>filippine</MADE_IN>
		<COMPOSIZIONE>cotone</COMPOSIZIONE>
		<TAGLIA>40</TAGLIA>
		<PREZZO_UNITARIO>70.90</PREZZO_UNITARIO>
	</record>
	<record>
		<ID_ARTICOLO>8</ID_ARTICOLO>
		<CODICE_ART>20002Z008</CODICE_ART>
		<NOME_ARTICOLO>Pantalone svasato</NOME_ARTICOLO>
		<NOME_BRAND>etro</NOME_BRAND>
		<MADE_IN>filippine</MADE_IN>
		<COMPOSIZIONE>cotone</COMPOSIZIONE>
		<TAGLIA>41</TAGLIA>
		<PREZZO_UNITARIO>70.90</PREZZO_UNITARIO>
	</record>
	<record>
		<ID_ARTICOLO>9</ID_ARTICOLO>
		<CODICE_ART>20002Z009</CODICE_ART>
		<NOME_ARTICOLO>Pantalone svasato</NOME_ARTICOLO>
		<NOME_BRAND>etro</NOME_BRAND>
		<MADE_IN>filippine</MADE_IN>
		<COMPOSIZIONE>cotone</COMPOSIZIONE>
		<TAGLIA>42</TAGLIA>
		<PREZZO_UNITARIO>70.90</PREZZO_UNITARIO>
	</record>
	<record>
		<ID_ARTICOLO>10</ID_ARTICOLO>
		<CODICE_ART>20002Z010</CODICE_ART>
		<NOME_ARTICOLO>Pantalone svasato</NOME_ARTICOLO>
		<NOME_BRAND>etro</NOME_BRAND>
		<MADE_IN>filippine</MADE_IN>
		<COMPOSIZIONE>cotone</COMPOSIZIONE>
		<TAGLIA>43</TAGLIA>
		<PREZZO_UNITARIO>70.90</PREZZO_UNITARIO>
	</record>
	<record>
		<ID_ARTICOLO>11</ID_ARTICOLO>
		<CODICE_ART>20002Z011</CODICE_ART>
		<NOME_ARTICOLO>Pantalone svasato</NOME_ARTICOLO>
		<NOME_BRAND>etro</NOME_BRAND>
		<MADE_IN>filippine</MADE_IN>
		<COMPOSIZIONE>cotone</COMPOSIZIONE>
		<TAGLIA>44</TAGLIA>
		<PREZZO_UNITARIO>70.90</PREZZO_UNITARIO>
	</record>
	<record>
		<ID_ARTICOLO>12</ID_ARTICOLO>
		<CODICE_ART>20002Z012</CODICE_ART>
		<NOME_ARTICOLO>pantalone disco</NOME_ARTICOLO>
		<NOME_BRAND>etro</NOME_BRAND>
		<MADE_IN>china</MADE_IN>
		<COMPOSIZIONE>cotone</COMPOSIZIONE>
		<TAGLIA>40</TAGLIA>
		<PREZZO_UNITARIO>432.20</PREZZO_UNITARIO>
	</record>
	<record>
		<ID_ARTICOLO>13</ID_ARTICOLO>
		<CODICE_ART>20002Z013</CODICE_ART>
		<NOME_ARTICOLO>pantalone disco</NOME_ARTICOLO>
		<NOME_BRAND>etro</NOME_BRAND>
		<MADE_IN>china</MADE_IN>
		<COMPOSIZIONE>cotone</COMPOSIZIONE>
		<TAGLIA>41</TAGLIA>
		<PREZZO_UNITARIO>432.20</PREZZO_UNITARIO>
	</record>
	<record>
		<ID_ARTICOLO>14</ID_ARTICOLO>
		<CODICE_ART>20002Z014</CODICE_ART>
		<NOME_ARTICOLO>pantalone disco</NOME_ARTICOLO>
		<NOME_BRAND>etro</NOME_BRAND>
		<MADE_IN>china</MADE_IN>
		<COMPOSIZIONE>cotone</COMPOSIZIONE>
		<TAGLIA>42</TAGLIA>
		<PREZZO_UNITARIO>432.20</PREZZO_UNITARIO>
	</record>
	<record>
		<ID_ARTICOLO>15</ID_ARTICOLO>
		<CODICE_ART>20002Z015</CODICE_ART>
		<NOME_ARTICOLO>pantalone disco</NOME_ARTICOLO>
		<NOME_BRAND>etro</NOME_BRAND>
		<MADE_IN>china</MADE_IN>
		<COMPOSIZIONE>cotone</COMPOSIZIONE>
		<TAGLIA>43</TAGLIA>
		<PREZZO_UNITARIO>432.20</PREZZO_UNITARIO>
	</record>
	<record>
		<ID_ARTICOLO>16</ID_ARTICOLO>
		<CODICE_ART>20002Z016</CODICE_ART>
		<NOME_ARTICOLO>pantalone disco</NOME_ARTICOLO>
		<NOME_BRAND>etro</NOME_BRAND>
		<MADE_IN>china</MADE_IN>
		<COMPOSIZIONE>cotone</COMPOSIZIONE>
		<TAGLIA>44</TAGLIA>
		<PREZZO_UNITARIO>432.20</PREZZO_UNITARIO>
	</record>
	<record>
		<ID_ARTICOLO>17</ID_ARTICOLO>
		<CODICE_ART>20002Z017</CODICE_ART>
		<NOME_ARTICOLO>top trendy</NOME_ARTICOLO>
		<NOME_BRAND>etro</NOME_BRAND>
		<MADE_IN>filippine</MADE_IN>
		<COMPOSIZIONE>cotone</COMPOSIZIONE>
		<TAGLIA>S</TAGLIA>
		<PREZZO_UNITARIO>132.90</PREZZO_UNITARIO>
	</record>
	<record>
		<ID_ARTICOLO>18</ID_ARTICOLO>
		<CODICE_ART>20002Z018</CODICE_ART>
		<NOME_ARTICOLO>top trendy</NOME_ARTICOLO>
		<NOME_BRAND>etro</NOME_BRAND>
		<MADE_IN>filippine</MADE_IN>
		<COMPOSIZIONE>cotone</COMPOSIZIONE>
		<TAGLIA>M</TAGLIA>
		<PREZZO_UNITARIO>132.90</PREZZO_UNITARIO>
	</record>
	<record>
		<ID_ARTICOLO>19</ID_ARTICOLO>
		<CODICE_ART>20002Z019</CODICE_ART>
		<NOME_ARTICOLO>top trendy</NOME_ARTICOLO>
		<NOME_BRAND>etro</NOME_BRAND>
		<MADE_IN>filippine</MADE_IN>
		<COMPOSIZIONE>cotone</COMPOSIZIONE>
		<TAGLIA>L</TAGLIA>
		<PREZZO_UNITARIO>132.90</PREZZO_UNITARIO>
	</record>
	<record>
		<ID_ARTICOLO>20</ID_ARTICOLO>
		<CODICE_ART>20002Z020</CODICE_ART>
		<NOME_ARTICOLO>short bently</NOME_ARTICOLO>
		<NOME_BRAND>etro</NOME_BRAND>
		<MADE_IN>bangladesh</MADE_IN>
		<COMPOSIZIONE>lana</COMPOSIZIONE>
		<TAGLIA>36</TAGLIA>
		<PREZZO_UNITARIO>150.80</PREZZO_UNITARIO>
	</record>
	<record>
		<ID_ARTICOLO>21</ID_ARTICOLO>
		<CODICE_ART>20002Z021</CODICE_ART>
		<NOME_ARTICOLO>short bently</NOME_ARTICOLO>
		<NOME_BRAND>etro</NOME_BRAND>
		<MADE_IN>bangladesh</MADE_IN>
		<COMPOSIZIONE>lana</COMPOSIZIONE>
		<TAGLIA>37</TAGLIA>
		<PREZZO_UNITARIO>150.80</PREZZO_UNITARIO>
	</record>
	<record>
		<ID_ARTICOLO>22</ID_ARTICOLO>
		<CODICE_ART>20002Z022</CODICE_ART>
		<NOME_ARTICOLO>short bently</NOME_ARTICOLO>
		<NOME_BRAND>etro</NOME_BRAND>
		<MADE_IN>bangladesh</MADE_IN>
		<COMPOSIZIONE>lana</COMPOSIZIONE>
		<TAGLIA>38</TAGLIA>
		<PREZZO_UNITARIO>150.80</PREZZO_UNITARIO>
	</record>
	<record>
		<ID_ARTICOLO>23</ID_ARTICOLO>
		<CODICE_ART>20002Z023</CODICE_ART>
		<NOME_ARTICOLO>short bently</NOME_ARTICOLO>
		<NOME_BRAND>etro</NOME_BRAND>
		<MADE_IN>bangladesh</MADE_IN>
		<COMPOSIZIONE>lana</COMPOSIZIONE>
		<TAGLIA>40</TAGLIA>
		<PREZZO_UNITARIO>150.80</PREZZO_UNITARIO>
	</record>
	<record>
		<ID_ARTICOLO>24</ID_ARTICOLO>
		<CODICE_ART>20002Z024</CODICE_ART>
		<NOME_ARTICOLO>short bently</NOME_ARTICOLO>
		<NOME_BRAND>etro</NOME_BRAND>
		<MADE_IN>bangladesh</MADE_IN>
		<COMPOSIZIONE>lana</COMPOSIZIONE>
		<TAGLIA>41</TAGLIA>
		<PREZZO_UNITARIO>150.80</PREZZO_UNITARIO>
	</record>
	<record>
		<ID_ARTICOLO>25</ID_ARTICOLO>
		<CODICE_ART>20002Z025</CODICE_ART>
		<NOME_ARTICOLO>short bently</NOME_ARTICOLO>
		<NOME_BRAND>etro</NOME_BRAND>
		<MADE_IN>bangladesh</MADE_IN>
		<COMPOSIZIONE>lana</COMPOSIZIONE>
		<TAGLIA>42</TAGLIA>
		<PREZZO_UNITARIO>150.80</PREZZO_UNITARIO>
	</record>
	<record>
		<ID_ARTICOLO>26</ID_ARTICOLO>
		<CODICE_ART>20002Z026</CODICE_ART>
		<NOME_ARTICOLO>short bugatti</NOME_ARTICOLO>
		<NOME_BRAND>etro</NOME_BRAND>
		<MADE_IN>filippine</MADE_IN>
		<COMPOSIZIONE>lana</COMPOSIZIONE>
		<TAGLIA>36</TAGLIA>
		<PREZZO_UNITARIO>150.80</PREZZO_UNITARIO>
	</record>
	<record>
		<ID_ARTICOLO>27</ID_ARTICOLO>
		<CODICE_ART>20002Z027</CODICE_ART>
		<NOME_ARTICOLO>short bugatti</NOME_ARTICOLO>
		<NOME_BRAND>etro</NOME_BRAND>
		<MADE_IN>filippine</MADE_IN>
		<COMPOSIZIONE>lana</COMPOSIZIONE>
		<TAGLIA>37</TAGLIA>
		<PREZZO_UNITARIO>150.80</PREZZO_UNITARIO>
	</record>
	<record>
		<ID_ARTICOLO>28</ID_ARTICOLO>
		<CODICE_ART>20002Z028</CODICE_ART>
		<NOME_ARTICOLO>short bugatti</NOME_ARTICOLO>
		<NOME_BRAND>etro</NOME_BRAND>
		<MADE_IN>filippine</MADE_IN>
		<COMPOSIZIONE>lana</COMPOSIZIONE>
		<TAGLIA>38</TAGLIA>
		<PREZZO_UNITARIO>150.80</PREZZO_UNITARIO>
	</record>
	<record>
		<ID_ARTICOLO>29</ID_ARTICOLO>
		<CODICE_ART>20002Z029</CODICE_ART>
		<NOME_ARTICOLO>short mclaren</NOME_ARTICOLO>
		<NOME_BRAND>etro</NOME_BRAND>
		<MADE_IN>china</MADE_IN>
		<COMPOSIZIONE>lana</COMPOSIZIONE>
		<TAGLIA>40</TAGLIA>
		<PREZZO_UNITARIO>150.80</PREZZO_UNITARIO>
	</record>
	<record>
		<ID_ARTICOLO>30</ID_ARTICOLO>
		<CODICE_ART>20002Z030</CODICE_ART>
		<NOME_ARTICOLO>short bugatti</NOME_ARTICOLO>
		<NOME_BRAND>etro</NOME_BRAND>
		<MADE_IN>filippine</MADE_IN>
		<COMPOSIZIONE>lana</COMPOSIZIONE>
		<TAGLIA>41</TAGLIA>
		<PREZZO_UNITARIO>150.80</PREZZO_UNITARIO>
	</record>
	<record>
		<ID_ARTICOLO>31</ID_ARTICOLO>
		<CODICE_ART>20002Z031</CODICE_ART>
		<NOME_ARTICOLO>short bugatti</NOME_ARTICOLO>
		<NOME_BRAND>etro</NOME_BRAND>
		<MADE_IN>filippine</MADE_IN>
		<COMPOSIZIONE>lana</COMPOSIZIONE>
		<TAGLIA>42</TAGLIA>
		<PREZZO_UNITARIO>3</PREZZO_UNITARIO>
	</record>
	<record>
		<ID_ARTICOLO>32</ID_ARTICOLO>
		<CODICE_ART>20002Z032</CODICE_ART>
		<NOME_ARTICOLO>short mclaren</NOME_ARTICOLO>
		<NOME_BRAND>etro</NOME_BRAND>
		<MADE_IN>china</MADE_IN>
		<COMPOSIZIONE>lana</COMPOSIZIONE>
		<TAGLIA>36</TAGLIA>
		<PREZZO_UNITARIO>150.80</PREZZO_UNITARIO>
	</record>
	<record>
		<ID_ARTICOLO>33</ID_ARTICOLO>
		<CODICE_ART>20002Z033</CODICE_ART>
		<NOME_ARTICOLO>short mclaren</NOME_ARTICOLO>
		<NOME_BRAND>etro</NOME_BRAND>
		<MADE_IN>china</MADE_IN>
		<COMPOSIZIONE>lana</COMPOSIZIONE>
